name: linear_models
channels:
  - defaults
dependencies:
  - python=3.8
  - scikit-learn
  - jupyterlab
  - statsmodels
  - pandas
  - seaborn
  - r-base
  - r-tidyverse
  - r-broom
  - r-irkernel
  - conda-forge::r-fixest
  - conda-forge::r-patchwork